# Generated by Django 4.1.4 on 2023-02-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('author', models.TextField()),
                ('img', models.ImageField(upload_to='img/')),
                ('audio', models.FileField(upload_to='audio/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
